name: Fetch upstream

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git setup
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Fetch files
        shell: bash
        run: |
          export RELEASE=$(curl -s https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)
          if [ "${RELEASE}" != "$(cat ./stable.txt)" ]; then
            curl -vLO "https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt"
            git add ./stable.txt || true
            git commit -m "feat: ${RELEASE}" || true
            git push origin main || true
            git checkout -b ${RELEASE} main
          else
            git checkout ${RELEASE}
          fi

          curl -vLO https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml
          git add ./kubevirt-operator.yaml || true
          git commit -m "feat: ${RELEASE} kubevirt-operator.yaml" || true
          curl -vLO https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
          git add ./kubevirt-cr.yaml || true
          git commit -m "feat: ${RELEASE} kubevirt-cr.yaml" || true
          git push origin ${RELEASE} || true
