name: Fetch upstream

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git setup
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Fetch files
        shell: bash
        run: |
          export RELEASE=$(curl -s https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)
          if [ "${RELEASE}" != "$(cat ./stable.txt)" ]; then
            curl -sLO https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt
            git add ./stable.txt
            git commit -m "feat: ${RELEASE}"
            git push origin main
            git checkout -b ${RELEASE} main
          else
            git checkout ${RELEASE}
          fi
          
          curl -sLO https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml
          git add ./kubevirt-operator.yaml
          git commit -m "feat: ${RELEASE} kubevirt-operator.yaml"
          curl -sLO https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
          git add ./kubevirt-cr.yaml
          git commit -m "feat: ${RELEASE} kubevirt-cr.yaml"
          git push origin ${RELEASE}
